In [1]:
import sys  # used with os to add the repo root to Python's module search path
import os  # for working directory checks and building file paths
import requests  # for making HTTP requests, checking status codes, downloading page content
import re  # regex module - used to search text for patterns (like matching
           # price formats such as $9.99) instead of exact string matches
import pandas as pd  # for loading and exploring the domain CSV as a dataframe

sys.path.append(os.path.abspath(".."))
from src.subscription_checker import check_domain_full

In [2]:
print(os.getcwd())  # check what folder the notebook is currently running from -
                     # needed this to debug relative path issues when loading the CSV

c:\Users\josen\Desktop\pricing-wayback-scraper\notebooks

## Domain filtering: loading and exploring the CSV

In [3]:
df = pd.read_csv("../data/news_domain_cleaned_sim.csv")
print(df.shape)
df.describe(include="all")

(299, 5)

,domain,top_domain,traffic,primary_country_code,primary_country_share
count,299,299,2.990000e+02,299,299.000000
unique,299,299,NaN,44,NaN
top,news.google.com,google.com,NaN,US,NaN
freq,1,1,NaN,71,NaN
mean,NaN,NaN,4.659310e+08,NaN,0.768062
std,NaN,NaN,5.495275e+09,NaN,0.238369
min,NaN,NaN,3.546611e+07,NaN,0.092819
25%,NaN,NaN,4.660485e+07,NaN,0.701439
50%,NaN,NaN,6.427469e+07,NaN,0.857779
75%,NaN,NaN,9.642194e+07,NaN,0.939717
max,NaN,NaN,9.488165e+10,NaN,0.996658

In [4]:
df_sorted = df.sort_values(by="traffic", ascending=False) #First rank domains by popularity (more popular = first)
df_sorted.head(20)

,domain,top_domain,traffic,primary_country_code,primary_country_share
0,news.google.com,google.com,94881645895,US,0.192977
1,arz.m.wikipedia.org,wikipedia.org,5143703369,US,0.222355
2,au.sports.yahoo.com,yahoo.com,4495242317,US,0.487774
3,article.yahoo.co.jp,yahoo.co.jp,1846124587,JP,0.982874
4,weather.com,weather.com,1644982011,US,0.417399
5,social.technet.microsoft.com,microsoft.com,992365009,US,0.171637
6,sway.office.com,office.com,873983152,US,0.297375
7,finance.naver.com,naver.com,845945497,KR,0.916839
8,arabic.cnn.com,cnn.com,674632188,US,0.744267
9,myaccount.nytimes.com,nytimes.com,669840885,US,0.685587
10,bbc.co.uk,bbc.co.uk,647852950,GB,0.843033
11,blogs.oglobo.globo.com,globo.com,552564190,BR,0.946007
12,msn.com,msn.com,537797018,US,0.431830
13,hi-tech.mail.ru,mail.ru,537230306,RU,0.800243
14,account.bbc.com,bbc.com,518496077,US,0.237108
15,espn.com,espn.com,497440975,US,0.844790
16,uol.com.br,uol.com.br,480131794,BR,0.942385
17,keiba.rakuten.co.jp,rakuten.co.jp,452416491,JP,0.984069
18,dailymail.co.uk,dailymail.co.uk,414333038,GB,0.429527
19,cricbuzz.com,cricbuzz.com,401439171,IN,0.907459

## Naver finance.com — false positive discovery

In [5]:
naver_results = check_domain_full("finance.naver.com")
naver_results

[{'domain': 'finance.naver.com',
  'path': 'subscribe',
  'status': 200,
  'final_url': 'https://finance.naver.com/subscribe',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'membership',
  'status': 200,
  'final_url': 'https://finance.naver.com/membership',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'join',
  'status': 200,
  'final_url': 'https://finance.naver.com/join',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'pricing',
  'status': 200,
  'final_url': 'https://finance.naver.com/pricing',
  'verdict': 'positive',
  'price_matches': []}]

In [6]:
import sys # used with os to add the repo root to Python's module search path
import requests # for making HTTP requests and checking status codes and downloading page content
import re # regex  module used to search text for patterns (like matching
        # price formats such as $9.99) instead of exact string matches

sys.path.append(os.path.abspath(".."))

from src.subscription_checker import check_domain_full

In [7]:
import os # for working directory checks and building file paths
print(os.getcwd()) # check what folder the notebook is currently running from -
                   # needed this to debug relative path issues when loading the CSV

c:\Users\josen\Desktop\pricing-wayback-scraper\notebooks

In [8]:
import pandas as pd # for loading and exploring the domain CSV as a dataframe

df = pd.read_csv("../data/news_domain_cleaned_sim.csv")
print(df.shape)
df.describe(include="all")

(299, 5)

,domain,top_domain,traffic,primary_country_code,primary_country_share
count,299,299,2.990000e+02,299,299.000000
unique,299,299,NaN,44,NaN
top,news.google.com,google.com,NaN,US,NaN
freq,1,1,NaN,71,NaN
mean,NaN,NaN,4.659310e+08,NaN,0.768062
std,NaN,NaN,5.495275e+09,NaN,0.238369
min,NaN,NaN,3.546611e+07,NaN,0.092819
25%,NaN,NaN,4.660485e+07,NaN,0.701439
50%,NaN,NaN,6.427469e+07,NaN,0.857779
75%,NaN,NaN,9.642194e+07,NaN,0.939717
max,NaN,NaN,9.488165e+10,NaN,0.996658

In [9]:
df_sorted = df.sort_values(by="traffic", ascending=False)  # rank domains by popularity (more popular = first)
df_sorted.head(20)

,domain,top_domain,traffic,primary_country_code,primary_country_share
0,news.google.com,google.com,94881645895,US,0.192977
1,arz.m.wikipedia.org,wikipedia.org,5143703369,US,0.222355
2,au.sports.yahoo.com,yahoo.com,4495242317,US,0.487774
3,article.yahoo.co.jp,yahoo.co.jp,1846124587,JP,0.982874
4,weather.com,weather.com,1644982011,US,0.417399
5,social.technet.microsoft.com,microsoft.com,992365009,US,0.171637
6,sway.office.com,office.com,873983152,US,0.297375
7,finance.naver.com,naver.com,845945497,KR,0.916839
8,arabic.cnn.com,cnn.com,674632188,US,0.744267
9,myaccount.nytimes.com,nytimes.com,669840885,US,0.685587
10,bbc.co.uk,bbc.co.uk,647852950,GB,0.843033
11,blogs.oglobo.globo.com,globo.com,552564190,BR,0.946007
12,msn.com,msn.com,537797018,US,0.431830
13,hi-tech.mail.ru,mail.ru,537230306,RU,0.800243
14,account.bbc.com,bbc.com,518496077,US,0.237108
15,espn.com,espn.com,497440975,US,0.844790
16,uol.com.br,uol.com.br,480131794,BR,0.942385
17,keiba.rakuten.co.jp,rakuten.co.jp,452416491,JP,0.984069
18,dailymail.co.uk,dailymail.co.uk,414333038,GB,0.429527
19,cricbuzz.com,cricbuzz.com,401439171,IN,0.907459

## Subscription detection: First tests and the Naver false positive

In [10]:
naver_results = check_domain_full("finance.naver.com")
naver_results

[{'domain': 'finance.naver.com',
  'path': 'subscribe',
  'status': 200,
  'final_url': 'https://finance.naver.com/subscribe',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'membership',
  'status': 200,
  'final_url': 'https://finance.naver.com/membership',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'join',
  'status': 200,
  'final_url': 'https://finance.naver.com/join',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'finance.naver.com',
  'path': 'pricing',
  'status': 200,
  'final_url': 'https://finance.naver.com/pricing',
  'verdict': 'positive',
  'price_matches': []}]

In [11]:
# quick live check: does the NYT subscribe page contain a price-shaped
# match in its raw HTML? (see CHALLENGES.md - this finds "$1" but it
# turns out to be JS code, not a real price - see limitation note below)
response = requests.get("https://www.nytimes.com/subscription?campaignId=9FRJJ")
re.search(r"\$\d+(\.\d{2})?", response.text)

In [12]:
# LIMITATION: requests.get() only returns raw HTML/JS source, not what a
# browser actually renders after running JavaScript. Tested against
# nytimes.com/subscription, the only "$" match found was inside a
# JS utility function (a regex backreference "$1", unrelated to pricing),
# not real page content. This suggests pricing on JS-heavy sites is
# rendered client-side and won't be visible to this method.
# Content-based price detection is therefore unreliable for such sites;
# these are routed to manual review rather than trusted automatically.

## Wayback Machine snapshot retrieval

In [13]:
from src.wayback_client import get_wayback_snapshots
from src.wayback_snapshot_fetcher import fetch_snapshot_price, sample_snapshots_across_range

In [14]:
snapshots = get_wayback_snapshots("nytimes.com/subscription")
len(snapshots)  # number of snapshots for nyt over 5 years (2021 - 2026)

HTTPError: 429 Client Error: Too Many Requests for url: https://web.archive.org/cdx/search/cdx?url=nytimes.com%2Fsubscription&from=20210101&to=20260101&output=json&filter=statuscode%3A200&collapse=timestamp%3A8

In [15]:
snapshots = get_wayback_snapshots("nytimes.com/subscription")
len(snapshots)  # number of snapshots for nyt over 5 years (2021 - 2026)

HTTPError: 429 Client Error: Too Many Requests for url: https://web.archive.org/cdx/search/cdx?url=nytimes.com%2Fsubscription&from=20210101&to=20260101&output=json&filter=statuscode%3A200&collapse=timestamp%3A8

In [16]:
sample = sample_snapshots_across_range(snapshots, n=8)
sample

NameError: name 'snapshots' is not defined

In [17]:
results = [fetch_snapshot_price(s) for s in sample]
results

NameError: name 'sample' is not defined

## Testing detection on additional domains (WSJ, Guardian, CNN)

In [18]:
wsj_results = check_domain_full("www.wsj.com")
wsj_results

[{'domain': 'www.wsj.com',
  'path': 'subscribe',
  'status': 403,
  'final_url': 'https://www.wsj.com/subscribe',
  'verdict': 'manual negative',
  'price_matches': None},
 {'domain': 'www.wsj.com',
  'path': 'membership',
  'status': 403,
  'final_url': 'https://www.wsj.com/membership',
  'verdict': 'manual negative',
  'price_matches': None},
 {'domain': 'www.wsj.com',
  'path': 'join',
  'status': 403,
  'final_url': 'https://www.wsj.com/join',
  'verdict': 'manual negative',
  'price_matches': None},
 {'domain': 'www.wsj.com',
  'path': 'pricing',
  'status': 403,
  'final_url': 'https://www.wsj.com/pricing',
  'verdict': 'manual negative',
  'price_matches': None}]

In [19]:
guardian_results = check_domain_full("www.theguardian.com")
guardian_results

[{'domain': 'www.theguardian.com',
  'path': 'subscribe',
  'status': 200,
  'final_url': 'https://support.theguardian.com/uk/subscribe/paper?utm_source=print&utm_medium=inpaper-g&utm_campaign=PRESS_VHD_0620_PS&CMP_TU=macqn&CMP_BUNIT=subs',
  'verdict': 'likely positive',
  'price_matches': [{'match': '$15',
    'context': '{"nudgeCopy":{"heading":"Support fearless journalism for <s>$15</s> $7.5/month","body":"Get unlimited access to our indepen'},
   {'match': '$7',
    'context': 'opy":{"heading":"Support fearless journalism for <s>$15</s> $7.5/month","body":"Get unlimited access to our independent re'},
   {'match': '$20',
    'context': '{"nudgeCopy":{"heading":"Support fearless journalism for <s>$20</s> $10/month","body":"Get unlimited access to our independ'},
   {'match': '$10',
    'context': 'opy":{"heading":"Support fearless journalism for <s>$20</s> $10/month","body":"Get unlimited access to our independent repo'},
   {'match': '$15',
    'context': '{"nudgeCopy":{"heading":"Support fearless journalism for <s>$15</s> $7.50/month","body":"Get unlimited access to our indepe'},
   {'match': '$7.50',
    'context': 'opy":{"heading":"Support fearless journalism for <s>$15</s> $7.50/month","body":"Get unlimited access to our independent repo'},
   {'match': '$28',
    'context': '{"nudgeCopy":{"heading":"Support fearless journalism for <s>$28</s> $14/month","body":"Get full access to our independent r'},
   {'match': '$14',
    'context': 'opy":{"heading":"Support fearless journalism for <s>$28</s> $14/month","body":"Get full access to our independent reporting'},
   {'match': '$30',
    'context': '{"nudgeCopy":{"heading":"Support fearless journalism for <s>$30</s> $15/month","body":"Get full access to our independent r'},
   {'match': '$15',
    'context': 'opy":{"heading":"Support fearless journalism for <s>$30</s> $15/month","body":"Get full access to our independent reporting'}]},
 {'domain': 'www.theguardian.com',
  'path': 'membership',
  'status': 200,
  'final_url': 'https://www.theguardian.com/membership',
  'verdict': 'positive',
  'price_matches': []},
 {'domain': 'www.theguardian.com',
  'path': 'join',
  'status': 404,
  'final_url': 'https://www.theguardian.com/join',
  'verdict': 'clean negative',
  'price_matches': None},
 {'domain': 'www.theguardian.com',
  'path': 'pricing',
  'status': 404,
  'final_url': 'https://www.theguardian.com/pricing',
  'verdict': 'clean negative',
  'price_matches': None}]

In [20]:
cnn_results = check_domain_full("edition.cnn.com")
cnn_results

[{'domain': 'edition.cnn.com',
  'path': 'subscribe',
  'status': 200,
  'final_url': 'https://edition.cnn.com/subscription',
  'verdict': 'likely positive',
  'price_matches': [{'match': '$1.99',
    'context': '="true"\n>\n        Unlock two months of unlimited access for $1.99/month.\n</h2>\n\n  \n    \n    \n    \n\n<div class="subscription-c'},
   {'match': '$69.99',
    'context': 'ss="subscription-card-grouped-products__pricing-info-price">$69.99</span>\n                        <span class="subscription-ca'},
   {'match': '$1.99',
    'context': 'ss="subscription-card-grouped-products__pricing-info-price">$1.99</span>\n                        <span class="subscription-ca'},
   {'match': '$29.99',
    'context': 'ss="subscription-card-grouped-products__pricing-info-price">$29.99</span>\n                        <span class="subscription-ca'},
   {'match': '$3.99',
    'context': 'ss="subscription-card-grouped-products__pricing-info-price">$3.99</span>\n                        <span class="subscription-ca'},
   {'match': '$1.99',
    'context': 'ubscribers via http://cnn.com  and participating providers. $1.99/month plus applicable tax billed immediately. Discount for '},
   {'match': '$6.99',
    'context': 'atically renews monthly at the then-current full price (now $6.99/month plus applicable tax) unless canceled. Discount subjec'},
   {'match': '$1',
    'context': '!d(c(f(e),n),c(f(t),n))),makeLinks:e=>e.replace(h,\'<a href="$1">$1</a>\'),ensureArray:$,isOfType:(e,t)=>$(e).includes(t),ge'},
   {'match': '$1',
    'context': '(f(e),n),c(f(t),n))),makeLinks:e=>e.replace(h,\'<a href="$1">$1</a>\'),ensureArray:$,isOfType:(e,t)=>$(e).includes(t),getHos'},
   {'match': '$1',
    'context': ' ${o} hora${o>1?"s":""}`,i>0&&(n=n.replace(/hora(s?)$/,`hora$1 y ${i}${i>1?" minutos":" minuto"}`)),n):$(r,t)},e.exports.f'},
   {'match': '$1',
    'context': '_BYTES;return t=this.toString("hex",0,r).replace(/(.{2})/g,"$1 ").trim(),this.length>r&&(t+=" ... "),"<Buffer "+t+">"},o&&'},
   {'match': '$1',
    'context': 'tps?:\\/\\//,"").replace(/\\\\/g,"\\\\\\\\").replace(/([\\/|:])/g,"\\\\$1"):e,delete i.escapeterm,u(r,"body.query",{[s]:{query:l,fiel'},
   {'match': '$1',
    'context': 'ttps?:\\/\\//,"").replace(/\\\\/g,"\\\\\\\\").replace(/([/|:])/g,"\\\\$1"),fields:o(r)?r:[r]}}),e.exports.ids=e=>({ids:{values:e}}),'},
   {'match': '$41.99',
    'context': 'ual plan subscribers via cnn.com & participating providers. $41.99 billed immediately. Discount for first year only. After tha'},
   {'match': '$69.99',
    'context': 'automatically renews yearly at then-current full price (now $69.99 plus applicable tax) unless cancelled. Discount subject to '},
   {'match': '$34.99',
    'context': 'ual plan subscribers via cnn.com & participating providers. $34.99 billed immediately. Discount for first year only. After tha'},
   {'match': '$69.99',
    'context': 'automatically renews yearly at then-current full price (now $69.99 plus applicable tax) unless cancelled. Discount subject to '},
   {'match': '$1',
    'context': 'Unlock unlimited articles with the Basic plan for less than $1/week.":"Get unlimited articles, plus streaming, shows & fil'},
   {'match': '$1',
    'context': 'et unlimited access for ${d&&!c?"a special rate":"less than $1/week"}.`,E=c&&n.get("PAYWALL_SUBONLY_VARIATION_ENABLED"),m='},
   {'match': '$1',
    'context': '"(\\\\s|&nbsp;|--|&[mn]dash;|"+n+"|&#x201[34])\'(?=\\\\w)","g"),"$1&#8216;")).replace(RegExp("("+t+")\'","g"),"$1&#8217;")).repl'},
   {'match': '$1',
    'context': '(?=\\\\w)","g"),"$1&#8216;")).replace(RegExp("("+t+")\'","g"),"$1&#8217;")).replace(RegExp("("+a+"?)\'(?=\\\\s|s\\\\b)","g"),"$1&#'},
   {'match': '$1',
    'context': ',"$1&#8217;")).replace(RegExp("("+a+"?)\'(?=\\\\s|s\\\\b)","g"),"$1&#8217;")).replace(/\'/g,"&#8216;")).replace(RegExp("(\\\\s|&nb'},
   {'match': '$1',
    'context': '"(\\\\s|&nbsp;|--|&[mn]dash;|"+n+\'|&#x201[34])"(?=\\\\w)\',"g"),"$1&#8220;")).replace(RegExp("("+t+\')"\',"g"),"$1&#8221;")).repl'},
   {'match': '$1',
    'context': '(?=\\\\w)\',"g"),"$1&#8220;")).replace(RegExp("("+t+\')"\',"g"),"$1&#8221;")).replace(RegExp("("+a+\'?)"(?=\\\\s)\',"g"),"$1&#8221;'},
   {'match': '$1',
    'context': ',"g"),"$1&#8221;")).replace(RegExp("("+a+\'?)"(?=\\\\s)\',"g"),"$1&#8221;")).replace(/"/g,"&#8220;")},n=function(e){return e=('},
   {'match': '$1',
    'context': 'eturn e=(e=(e=(e=(e=(e=(e=(e=(e=e.replace(/\'(tis|twas)/gi,"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2'},
   {'match': '$1',
    'context': '=(e=e.replace(/\'(tis|twas)/gi,"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1'},
   {'match': '$1',
    'context': ',"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1'},
   {'match': '$2',
    'context': '$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")'},
   {'match': '$1',
    'context': '$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|'},
   {'match': '$2',
    'context': ')).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|\'(.'},
   {'match': '$1',
    'context': '$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,'},
   {'match': '$1',
    'context': '")).replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/'},
   {'match': '$2',
    'context': '.replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,'},
   {'match': '$3',
    'context': 'eplace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$'},
   {'match': '$4',
    'context': 'ace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$'},
   {'match': '$1',
    'context': '[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*'},
   {'match': '$1',
    'context': '3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)['},
   {'match': '$2',
    'context': '4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"]'},
   {'match': '$1',
    'context': 'place(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.def'},
   {'match': '$2',
    'context': 'ce(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.defaul'},
   {'match': '$1',
    'context': '(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.default}}]); \n /* window.modules["613"] *'},
   {'match': '$2',
    'context': '^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.default}}]); \n /* window.modules["613"] */ "'},
   {'match': '$1',
    'context': 'tor||" ",decimalSeperator=e&&e.decimalSeperator||",";var n="$1"+thousandSeperator,o=number.split(decimalSeperator)[0],a=pr'},
   {'match': '$1',
    'context': 'ush(""),r.replace(n,function(r,t,n,a){e.push(n?a.replace(o,"$1"):t||r)}),e});r.exports=a},function(r,e){var t=/\\s/;r.expor'},
   {'match': '$1',
    'context': 'mart "+X+ig]],[/(av(?:ast|g|ira))\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1 Secure"+ig],m],[/norton\\/([\\w\\.]+)/i],[m,[u,"Norton Private'},
   {'match': '$1',
    'context': '\\w\\.]*)/i],[m,[u,"360"]],[/\\b(qq)\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1Browser"],m],[/(oculus|sailfish|huawei|vivo|pico)browser\\/(['},
   {'match': '$1',
    'context': 'sailfish|huawei|vivo|pico)browser\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1"+ig],m],[/samsungbrowser\\/([\\w\\.]+)/i],[m,[u,it+" Internet"'},
   {'match': '$1',
    'context': '349hijorstuw]+)( bui|\\)).+silk\\//i],[[v,/(.+)/g,"Fire Phone $1"],[h,R],[p,x]],[/(playbook);[-\\w\\),; ]+(rim)/i],[v,h,[p,y]]'},
   {'match': '$1',
    'context': '\\d+ +\\([\\w\\+ ]*; *([\\w\\d][^;]*);([^;]*)/i],[[h,/.+\\/(\\w+)/,"$1",iA,{LG:"lge"}],[v,iF],[p,C]],[/(playstation \\w+)/i],[v,[h,'},
   {'match': '$1',
    'context': ')/i],[m,u],[/(ubuntu) ([\\w\\.]+) like android/i],[[u,/(.+)/,"$1 Touch"],m],[/(harmonyos)[\\/ ]?([\\d\\.]*)/i,/(android|bada|bl'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$"));t=window.document.cookie.replace(o,"$1"),t=p.decode(t);var n="".concat(this.api.cookie.version,"|"'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$")),o=window.document.cookie.replace(t,"$1");o&&(e=Date.parse(o))}catch(e){console.log("Could not retr'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$")),t=window.document.cookie.replace(o,"$1");return n.decode(t)}catch(o){console.log("DaltonSDK Error '},
   {'match': '$1',
    'context': 'ush(""),e.replace(l,function(e,s,u,l){r.push(u?l.replace(o,"$1"):s||e)}),r});e.exports=p}}]); \n /* window.modules["2449"] '},
   {'match': '$1',
    'context': 'e(/hasOwnProperty|(function).*?(?=\\\\\\()| for .+?(?=\\\\\\])/g,"$1.*?")+"$");t.exports=function(t){return!(!p(t)||n(t))&&(r(t)'}]},
 {'domain': 'edition.cnn.com',
  'path': 'membership',
  'status': 404,
  'final_url': 'https://edition.cnn.com/membership',
  'verdict': 'clean negative',
  'price_matches': None},
 {'domain': 'edition.cnn.com',
  'path': 'join',
  'status': 200,
  'final_url': 'https://edition.cnn.com/',
  'verdict': 'manual positive',
  'price_matches': [{'match': '$65',
    'context': 'le="headline">Trump’s longtime teleprompter operator to pay $65,000 fine to settle insider-trading case</span>\n            '},
   {'match': '$5',
    'context': 'text" data-editable="headline">Young adults under 21 traded $5 billion on Kalshi this year, amid prediction market frenzy<'},
   {'match': '$1',
    'context': '!d(c(f(e),n),c(f(t),n))),makeLinks:e=>e.replace(h,\'<a href="$1">$1</a>\'),ensureArray:$,isOfType:(e,t)=>$(e).includes(t),ge'},
   {'match': '$1',
    'context': '(f(e),n),c(f(t),n))),makeLinks:e=>e.replace(h,\'<a href="$1">$1</a>\'),ensureArray:$,isOfType:(e,t)=>$(e).includes(t),getHos'},
   {'match': '$1',
    'context': ' ${o} hora${o>1?"s":""}`,i>0&&(n=n.replace(/hora(s?)$/,`hora$1 y ${i}${i>1?" minutos":" minuto"}`)),n):$(r,t)},e.exports.f'},
   {'match': '$1',
    'context': '_BYTES;return t=this.toString("hex",0,r).replace(/(.{2})/g,"$1 ").trim(),this.length>r&&(t+=" ... "),"<Buffer "+t+">"},o&&'},
   {'match': '$1',
    'context': 'ocument.referrer).replace(/^http(?:s)?:\\/\\/([\\w\\-.]+).*$/i,"$1").toLowerCase();return/^([\\w-]+\\.)*money\\.cnn\\.com$/.test(e'},
   {'match': '$1',
    'context': 'tps?:\\/\\//,"").replace(/\\\\/g,"\\\\\\\\").replace(/([\\/|:])/g,"\\\\$1"):e,delete i.escapeterm,u(r,"body.query",{[s]:{query:l,fiel'},
   {'match': '$1',
    'context': 'ttps?:\\/\\//,"").replace(/\\\\/g,"\\\\\\\\").replace(/([/|:])/g,"\\\\$1"),fields:o(r)?r:[r]}}),e.exports.ids=e=>({ids:{values:e}}),'},
   {'match': '$41.99',
    'context': 'ual plan subscribers via cnn.com & participating providers. $41.99 billed immediately. Discount for first year only. After tha'},
   {'match': '$69.99',
    'context': 'automatically renews yearly at then-current full price (now $69.99 plus applicable tax) unless cancelled. Discount subject to '},
   {'match': '$34.99',
    'context': 'ual plan subscribers via cnn.com & participating providers. $34.99 billed immediately. Discount for first year only. After tha'},
   {'match': '$69.99',
    'context': 'automatically renews yearly at then-current full price (now $69.99 plus applicable tax) unless cancelled. Discount subject to '},
   {'match': '$1',
    'context': 'Unlock unlimited articles with the Basic plan for less than $1/week.":"Get unlimited articles, plus streaming, shows & fil'},
   {'match': '$1',
    'context': 'et unlimited access for ${d&&!c?"a special rate":"less than $1/week"}.`,E=c&&n.get("PAYWALL_SUBONLY_VARIATION_ENABLED"),m='},
   {'match': '$1',
    'context': '"(\\\\s|&nbsp;|--|&[mn]dash;|"+n+"|&#x201[34])\'(?=\\\\w)","g"),"$1&#8216;")).replace(RegExp("("+t+")\'","g"),"$1&#8217;")).repl'},
   {'match': '$1',
    'context': '(?=\\\\w)","g"),"$1&#8216;")).replace(RegExp("("+t+")\'","g"),"$1&#8217;")).replace(RegExp("("+a+"?)\'(?=\\\\s|s\\\\b)","g"),"$1&#'},
   {'match': '$1',
    'context': ',"$1&#8217;")).replace(RegExp("("+a+"?)\'(?=\\\\s|s\\\\b)","g"),"$1&#8217;")).replace(/\'/g,"&#8216;")).replace(RegExp("(\\\\s|&nb'},
   {'match': '$1',
    'context': '"(\\\\s|&nbsp;|--|&[mn]dash;|"+n+\'|&#x201[34])"(?=\\\\w)\',"g"),"$1&#8220;")).replace(RegExp("("+t+\')"\',"g"),"$1&#8221;")).repl'},
   {'match': '$1',
    'context': '(?=\\\\w)\',"g"),"$1&#8220;")).replace(RegExp("("+t+\')"\',"g"),"$1&#8221;")).replace(RegExp("("+a+\'?)"(?=\\\\s)\',"g"),"$1&#8221;'},
   {'match': '$1',
    'context': ',"g"),"$1&#8221;")).replace(RegExp("("+a+\'?)"(?=\\\\s)\',"g"),"$1&#8221;")).replace(/"/g,"&#8220;")},n=function(e){return e=('},
   {'match': '$1',
    'context': 'eturn e=(e=(e=(e=(e=(e=(e=(e=(e=e.replace(/\'(tis|twas)/gi,"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2'},
   {'match': '$1',
    'context': '=(e=e.replace(/\'(tis|twas)/gi,"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1'},
   {'match': '$1',
    'context': ',"’$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1'},
   {'match': '$2',
    'context': '$1")).replace(/\'(\\d0s)/gi,"’$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")'},
   {'match': '$1',
    'context': '$1")).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|'},
   {'match': '$2',
    'context': ')).replace(/(\\S)\'(\\S)/gi,"$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|\'(.'},
   {'match': '$1',
    'context': '$1’$2").replace(/(\\S)\'(\\S)/gi,"$1’$2")).replace(/\'(n)\'/gi,"’$1’")).replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,'},
   {'match': '$1',
    'context': '")).replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/'},
   {'match': '$2',
    'context': '.replace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,'},
   {'match': '$3',
    'context': 'eplace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$'},
   {'match': '$4',
    'context': 'ace(/(^|\\s)(?:"(.*?)"|\'(.*?[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$'},
   {'match': '$1',
    'context': '[^(?:o|ol|s)])\')(\\s|$)/,"$1‘$2$3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*'},
   {'match': '$1',
    'context': '3’$4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)['},
   {'match': '$2',
    'context': '4")).replace(/(o|ol)\'/gi,"$1’")).replace(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"]'},
   {'match': '$1',
    'context': 'place(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.def'},
   {'match': '$2',
    'context': 'ce(/(s)\'(\\s|$)/gi,"$1’$2")).replace(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.defaul'},
   {'match': '$1',
    'context': '(/(^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.default}}]); \n /* window.modules["613"] *'},
   {'match': '$2',
    'context': '^|\\s)[\'"](.*?)/gi,"$1‘$2")).replace(/(.*?)[\'"](\\s|$)/gi,"$1’$2")},e.exports=$.default}}]); \n /* window.modules["613"] */ "'},
   {'match': '$1',
    'context': 'tor||" ",decimalSeperator=e&&e.decimalSeperator||",";var n="$1"+thousandSeperator,o=number.split(decimalSeperator)[0],a=pr'},
   {'match': '$1',
    'context': 'ush(""),r.replace(n,function(r,t,n,a){e.push(n?a.replace(o,"$1"):t||r)}),e});r.exports=a},function(r,e){var t=/\\s/;r.expor'},
   {'match': '$1',
    'context': 'mart "+X+ig]],[/(av(?:ast|g|ira))\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1 Secure"+ig],m],[/norton\\/([\\w\\.]+)/i],[m,[u,"Norton Private'},
   {'match': '$1',
    'context': '\\w\\.]*)/i],[m,[u,"360"]],[/\\b(qq)\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1Browser"],m],[/(oculus|sailfish|huawei|vivo|pico)browser\\/(['},
   {'match': '$1',
    'context': 'sailfish|huawei|vivo|pico)browser\\/([\\w\\.]+)/i],[[u,/(.+)/,"$1"+ig],m],[/samsungbrowser\\/([\\w\\.]+)/i],[m,[u,it+" Internet"'},
   {'match': '$1',
    'context': '349hijorstuw]+)( bui|\\)).+silk\\//i],[[v,/(.+)/g,"Fire Phone $1"],[h,R],[p,x]],[/(playbook);[-\\w\\),; ]+(rim)/i],[v,h,[p,y]]'},
   {'match': '$1',
    'context': '\\d+ +\\([\\w\\+ ]*; *([\\w\\d][^;]*);([^;]*)/i],[[h,/.+\\/(\\w+)/,"$1",iA,{LG:"lge"}],[v,iF],[p,C]],[/(playstation \\w+)/i],[v,[h,'},
   {'match': '$1',
    'context': ')/i],[m,u],[/(ubuntu) ([\\w\\.]+) like android/i],[[u,/(.+)/,"$1 Touch"],m],[/(harmonyos)[\\/ ]?([\\d\\.]*)/i,/(android|bada|bl'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$"));t=window.document.cookie.replace(o,"$1"),t=p.decode(t);var n="".concat(this.api.cookie.version,"|"'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$")),o=window.document.cookie.replace(t,"$1");o&&(e=Date.parse(o))}catch(e){console.log("Could not retr'},
   {'match': '$1',
    'context': '\\\\s*([^;]*).*$)|^.*$")),t=window.document.cookie.replace(o,"$1");return n.decode(t)}catch(o){console.log("DaltonSDK Error '},
   {'match': '$1',
    'context': 'ush(""),e.replace(l,function(e,s,u,l){r.push(u?l.replace(o,"$1"):s||e)}),r});e.exports=p}}]); \n /* window.modules["2447"] '},
   {'match': '$1',
    'context': 'e(/hasOwnProperty|(function).*?(?=\\\\\\()| for .+?(?=\\\\\\])/g,"$1.*?")+"$");t.exports=function(t){return!(!p(t)||n(t))&&(r(t)'}]},
 {'domain': 'edition.cnn.com',
  'path': 'pricing',
  'status': 404,
  'final_url': 'https://edition.cnn.com/pricing',
  'verdict': 'clean negative',
  'price_matches': None}]

## CSV output

In [21]:
from src.csv_writer import write_pricing_csv

write_pricing_csv(cnn_results, output_path="../data/pricing_results_test.csv")

[{'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$69.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$29.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$3.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$6.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$41.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$69.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$34.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$69.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$3',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$4',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/subscription',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/membership',
  'snapshot_timestamp': '',
  'pricing_type': '',
  'price_shown': '',
  'reason_code': 'no_price_found'},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$65',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$5',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$41.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$69.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$34.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$69.99',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$3',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$4',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$2',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},
 {'domain': 'edition.cnn.com',
  'pricing_page_url': 'https://edition.cnn.com/',
  'snapshot_timestamp': '',
  'pricing_type': 'unspecified',
  'price_shown': '$1',
  'reason_code': ''},

In [22]:
nyt_snapshot_results = [fetch_snapshot_price(s) for s in sample]
for r in nyt_snapshot_results:
    r["domain"] = "nytimes.com"  # fetch_snapshot_price doesn't include domain by default
write_pricing_csv(nyt_snapshot_results, output_path="../data/pricing_results_nyt_snapshots.csv")

NameError: name 'sample' is not defined